name: ASP.NET Core CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        nsq:
          - v1.0.0-compat
          - v1.2.0

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Start nsqd
      run: docker-compose up -d
      env:
        NSQ_TAG: ${{ matrix.nsq }}

    - name: Run tests
      run: dotnet test
